name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t imrohit68/collab-editor:latest .
      - name: Publish Image to Docker Hub
        run: docker push imrohit68/collab-editor:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH Key to Agent
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-203-76-146.ap-south-1.compute.amazonaws.com "
          sudo docker pull imrohit68/collab-editor:latest && \
          sudo docker stop collab-editor-container || true && \
          sudo docker rm collab-editor-container || true && \
          sudo docker run -d -p 8080:8080 --name collab-editor-container imrohit68/collab-editor:latest"
